### ISSUE TITLE
Shake of

### ISSUE THREAD

**Issue by Qugar** [x753/Lethal-Company-Peepers#1]
Is there a way to get the peepers off your body without causing any damage? If not, would it be possible to establish a way?

I have no idea how much effort it would be, but maybe it would be possible for the peepers to jump from one player to another?

**Comment by x753** [comment]
There are ways to get them off without taking damage already. Experiment with different equipment.

**Comment by Qugar** [comment]
Ah ok, we don't use regular flashlights anymore, we use the Advanced Company tactical helmets, but now flashlights have a use for us again. However, I would still find peepers passed from player to player funny.

Thank you for your response. :thumbsup:
