### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Th3GamingDonkey** [x753/Lethal-Company-Peepers#2]
-Peepers fall off when the player is teleported
-More Customization, like which moons they spawn on

**Comment by x753** [comment]
Moon-specific spawn rates is something I'll probably have by the 1.0 release. As for teleporting, I don't plan on adding that because they'd be a bit too easy to deal with that way.

**Comment by maxumusprime** [comment]
I like the teleportation idea, with one of the following caveats:
1. The player could take some damage when the peepers are forcibly removed by teleportation. (10 damage?)
2. Teleportation removal is optional config, off by default.

**Comment by Th3GamingDonkey** [comment]
When is the 1.0 release?

**Comment by x753** [comment]
It may be after the next vanilla update unless I get a sudden burst of free time and inspiration.

**Comment by EpicIsGabe** [comment]
Wondering if you will be updating to v50 beta?

**Comment by x753** [comment]
I'll be updating it for when v50 leaves beta because they're likely incompatible.

**Comment by Th3GamingDonkey** [comment]
is it updated for v50 with Moon spesific configs?

**Comment by x753** [comment]
It's updated for v50, but still not 1.0.0 yet.
