### ISSUE TITLE
Weight is saved if players died

### ISSUE THREAD

**Issue by SKYNETCyber** [x753/Lethal-Company-Peepers#3]
When I was playing with my group they complain that if they died with the peepers on them the weight would be permanent until we restarted the game

**Comment by x753** [comment]
When a player is killed their carry weight is set back to normal, were they killed in an unusual way? (such as a modded enemy)

**Comment by SKYNETCyber** [comment]
He mention that he got killed by a eyeless dog when the peepers alert it so should be normal death. If the carry weight is supposed to reset will try readding it and seeing if I can get it to happen again today.

**Comment by x753** [comment]
This should be fixed in v1.0.0 which will be out shortly.
