### ISSUE TITLE
Please add more config for moons spawns

### ISSUE THREAD

**Issue by Th3GamingDonkey** [x753/Lethal-Company-Peepers#4]
V50 is out, and I really like the Idea that the Peepers, spawn in sandy maps and the tulip snakes spawn on forest maps.

they both have similar mechanics, but different enough to be interesting, but both on the same map is a bit too much

Could you add a config option to spawn chances of each moon?

**Comment by x753** [comment]
I'm adding a moon blacklist for v1.0.0.
